apiVersion: apps/v1
kind: Deployment
metadata:
  name: vkapp1-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vkapp1
  template:
    metadata:
      labels:
        app: vkapp1
    spec:
      containers:
        - name: vkapp1
          image: vkasin/app1:102